name: Publish BlazorStaticMinimalBlog

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for accurate commit info

      - name: Install BlazorStatic.Templates and create the blog
        run: |
              dotnet new install BlazorStatic.Templates
              dotnet new BlazorStaticMinimalBlog -o BlazorStaticMinimalBlog

      - name: Push to by-build branch of BlazorStatic/BlazorStaticMinimalBlog
        run: |
          git init
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git remote add origin https://x-access-token:${{ secrets.BLAZORSTATICMINIMALBLOG_REPO_TOKEN }}@github.com/BlazorStatic/BlazorStaticMinimalBlog.git
          git checkout --orphan by-build
          git rm -rf .  # Remove all files to start fresh on the orphan branch
          cp -r BlazorStaticMinimalBlog/* .
          git add -A
          git commit -m "Publishing BlazorStaticMinimalBlog to orphaned by-build branch"
          git push -f origin by-build
        working-directory: BlazorStaticMinimalBlog
