name: Publish BlazorStaticMinimalBlog

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install BlazorStatic.Templates and create the blog
        run: |
              dotnet new install BlazorStatic.Templates
              dotnet new BlazorStaticMinimalBlog -o BlazorStaticMinimalBlog

      - name: Push to by-build branch of BlazorStatic/BlazorStaticMinimalBlog
        run: |
          git init --initial-branch=by-build
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git remote add origin https://x-access-token:${{ secrets.BLAZORSTATICMINIMALBLOG_REPO_TOKEN }}@github.com/BlazorStatic/BlazorStaticMinimalBlog.git
          git add .
          git commit -m "version 1.0.2"
          git push -f origin by-build
        working-directory: BlazorStaticMinimalBlog
